# Generated by Django 4.1.2 on 2022-11-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcategory',
            name='description',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
